RPRBLND-1900: Add Principle BSDF Emmision channel Support for USD_Hydra.
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #107
Opened 2021-09-21 15:17 UTC by DagerD

### PURPOSE
Need to add support for Principle BSDF Emission channel, now emission doesn't show any results with USD_Hydra plugin

### EFFECT OF CHANGE
Enable support of Principle BSDF Emission channel

### TECHNICAL STEPS
Fixed wrong formula for weight and source for color

2021-09-21 19:48 UTC, bnagirniak requested changes

2021-09-21 19:48 UTC, bnagirniak commented on src/hdusd/bl_nodes/nodes/shader.py
> +                'uber_emission_color': emission.data[:3],
this is incorrect, because emission NodeItem object could be a node or float. 
Same for emission_weight, we expect not only float, but node also.

2021-09-22 10:40 UTC, VascoPi reviewed
Emission power does not change if increase emission_strentgh for example to 20.0. Think you also need to multiply emission_color with emision_strength. Now emision_strength influence only emission_weight (ratio between diffuse and emission), which max value is 1.0.

2021-09-23 09:31 UTC, VascoPi approved these changes
Tested, works as expected.

2021-09-24 14:18 UTC, bnagirniak approved these changes
Looks good

2021-09-24 22:22 UTC, merged