RPRBLND-1370: Reroute nodes
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #135
Opened 2021-11-02 16:01 UTC by VascoPi

### PURPOSE
Add Reroute nodes to MaterialX, Shader/World Editor, USD Editor.
Optionally add Frame node.

### EFFECT OF CHANGE
Added Layout node category to MaterialX, Shader Editor, USD Editor.
Added Reroute and Frame nodes to MaterialX, Shader Editor, USD Editor.

### TECHNICAL STEPS
Registered new category Layout in USD, MaterialX, Shader Editor.
Changed get_input_link method so it skips all NodeReroute objects. It's has done in MxNode, NodeParser, USDNode.
In HDUSD_MATERIAL_PT_material_settings_surface, HDUSD_MATERIAL_PT_material_settings_displacement, changed draw method so it skips all NodeReroute objects.
Changed _reset_next method so it skips all NodeReroute objects in USDNode.

2021-11-02 16:57 UTC, bnagirniak requested changes
Suggested code improvement

2021-11-02 16:57 UTC, bnagirniak commented on src/hdusd/bl_nodes/node_parser.py
> +                node = link.from_node
Please move this code to utils/\_\_init__.py
```
    def pass_node_reroute(node)
        while isinstance(node, bpy.types.NodeReroute):
            if not node.inputs[0].links:
                return None

            link = node.inputs[0].links[0]
            if link.is_valid:
                node = link.from_node

        return node
```
and use it in other places

2021-11-03 15:11 UTC, DagerD approved these changes
Tested. Works ok.
Also commented in code

2021-11-04 15:29 UTC, bnagirniak approved these changes
Tested - works good

2021-11-05 15:58 UTC, merged