RPRBLND-1968: Improve MatX UI panel (should be more close to Blender Shading)
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #143
Opened 2021-11-08 15:48 UTC by VascoPi

### PURPOSE
Improve MatX UI panel (should be more close to Blender Shading).

### EFFECT OF CHANGE
Improved MatX UI panel.
Added UI element to animate property.
Fixed behavior Displacement output link/remove a node to Surface output.

### TECHNICAL STEPS
Made changes to MxNodeInputSocket.draw, so socket property has a different appearance according to context.
Redesign layout of the Material Properties panel, stuff like proportions, icons, position.
Changed values of  use_property_split, use_property_decorate in a few places to add animation UI items.
Fixed Displacement output link/remove node, pass to HDUSD_MATERIAL_OP_invoke_popup_shader_nodes correct input number input_num = int(input.identifier[-1]).

2021-11-09 15:17 UTC, bnagirniak requested changes
Some UI places should be improved, discussed offline

2021-11-09 15:17 UTC, bnagirniak commented on src/hdusd/mx_nodes/nodes/base_node.py
> +                new_layout = layout.split(factor=0.38)
factor=0.4 is standard

2021-11-11 14:37 UTC, DagerD requested changes
Tested. Works ok. Some improvements were discussed offline

2021-11-11 19:32 UTC, bnagirniak approved these changes
Tested - looks and works good.

2021-11-12 08:09 UTC, DagerD approved these changes
Tested. Works ok.

2021-11-15 03:05 UTC, bsavery requested changes
Merge error

2021-11-16 21:34 UTC, merged