RPRBLND-1971: Create Transform node dependent of object from scene
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #145
Opened 2021-11-12 08:04 UTC by DagerD

### PURPOSE
Should be looks like Instance node: select blender object and get transformation from that object and assign it to USD stage

### EFFECT OF CHANGE
- Changed UI for Transform node.
- Added new node "Transform by Empty object".

### TECHNICAL STEPS
- UI improvements for Transform node
- Reworked compute method for Transform node
- New node TrasformByEmptyObject - it gets transformation from choosen Empty object from scene.

2021-11-12 11:01 UTC, VascoPi requested changes
Some details were discussed offline.

2021-11-12 11:01 UTC, VascoPi commented on src/hdusd/usd_nodes/nodes/transformations.py
> +            matrix = Gf.Matrix4d(obj_matrix[0][0], obj_matrix[0][1], obj_matrix[0][2], 0,
Code improvements matrix = Gf.Matrix4d(obj.matrix_world.transposed()).

2021-11-12 15:39 UTC, VascoPi commented on src/hdusd/usd_nodes/nodes/transformations.py
> +    translation_x: bpy.props.FloatProperty(update=update_data, subtype='DISTANCE')
Code improvements:
```
 
    translation: bpy.props.FloatVectorProperty(update=update_data, unit='LENGTH')
    rotation: bpy.props.FloatVectorProperty(update=update_data, unit='ROTATION')
    scale: bpy.props.FloatVectorProperty(update=update_data, unit='NONE', default=(1.0, 1.0, 1.0))


    def draw_buttons(self, context, layout):
        col = layout.column()
        col.prop(self, 'name')
        col.separator()
        col.row().prop(self, 'translation',  text='Translation')
        col.row().prop(self, 'rotation', text='Rotation')
        col.row().prop(self, 'scale', text='Scale')
```

2021-11-12 18:16 UTC, bnagirniak requested changes
Some improvements are required

2021-11-12 18:16 UTC, bnagirniak commented on src/hdusd/usd_nodes/nodes/transformations.py
> +            root_prim.GetAttribute('xformOp:transform').Set(Gf.Matrix4d(obj.matrix_world.transposed()))
use get_transform() from export/object.py

2021-11-15 08:20 UTC, VascoPi approved these changes
Works well.

2021-11-15 19:31 UTC, bnagirniak approved these changes
Tested - works good

2021-11-15 19:31 UTC, bnagirniak commented on src/hdusd/usd_nodes/nodes/transformations.py
> +            self.reset()
add new line

2021-11-16 21:34 UTC, merged