fix_RPRBLND-1968: Improve MatX UI panel (should be more close to Blender Shading)
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #148
Opened 2021-11-17 14:36 UTC by VascoPi

### PURPOSE
Error with an older scene that contains uber shader.

### EFFECT OF CHANGE
Works as expected for a scene with uber shader.

### TECHNICAL STEPS
get a correct input index with output_node.inputs.find(self.bl_label).

2021-11-18 09:47 UTC, bnagirniak requested changes
Discussed offline, need to do some improvements in UI.

2021-11-18 18:43 UTC, bnagirniak requested changes
Code should be improved for better support.

2021-11-18 18:43 UTC, bnagirniak commented on src/hdusd/mx_nodes/nodes/base_node.py
> +        if not hasattr(node, 'nodedef'):    # handle MaterialX 1.37 nodes
Move `hasattr(node, 'nodedef')` to special function in utils/mx.py and use this function in all required places.
Possible function name `mx_node_ok()`

2021-11-19 08:27 UTC, bnagirniak commented on src/hdusd/mx_nodes/nodes/base_node.py
> +        if not hasattr(node, 'nodedef'):    # handle MaterialX 1.37 nodes
Or better create in mx_nodes/nodes/base_node.py function with name `is_node_ok()`

2021-11-19 14:00 UTC, bnagirniak reviewed
Small improvements

2021-11-19 14:00 UTC, bnagirniak commented on src/hdusd/mx_nodes/nodes/base_node.py
> +        return mx_utils.get_socket_color(socket_type)
simplify this to:
```
return mx_utils.get_socket_color(node.nodedef.getInput(self.name).getType() 
                                 if is_mx_node_valid(node) else 'undefined')
```

2021-11-19 14:00 UTC, bnagirniak commented on src/hdusd/mx_nodes/nodes/base_node.py
> +        return mx_utils.get_socket_color(socket_type)
Simplify this also

2021-11-19 20:27 UTC, bnagirniak approved these changes
Tested - works good.

2021-11-22 09:38 UTC, DagerD approved these changes
Tested. Works ok.

2021-11-23 15:45 UTC, merged