RPRBLND-1996: Improve Material X import/export
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #151
Opened 2021-11-18 13:21 UTC by DagerD

### PURPOSE
Improve MaterialX export by adding new options.

### EFFECT OF CHANGE
Added following options for MaterialX export:
1. Export MaterialX dependencies
2. Export bound textures
3. Folder name for bound textures

### TECHNICAL STEPS

- Operators modified with corresponded properties.
- separate export function to export_mx_to_file
- separate convert function to convert_mx_node_tree
- HDUSD_MATERIAL_OP_export_mx_file, HDUSD_MX_OP_export_file, HDUSD_MATERIAL_OP_convert_mx_node_tree now calls corresponded functions.

2021-11-19 16:12 UTC, bnagirniak requested changes
Need code improvements

2021-11-22 10:48 UTC, DagerD commented on src/hdusd/ui/mx_nodes.py
> +
no draw() here

2021-11-22 16:40 UTC, VascoPi approved these changes
Works well, some details were discussed offline.

2021-11-22 19:00 UTC, bnagirniak requested changes
Export operator UI can be improved by using draw(). Other improvements.

2021-11-23 15:07 UTC, bnagirniak approved these changes
Tested - works good

2021-11-23 15:48 UTC, bsavery requested changes
Fix conflicts.

2021-11-25 05:12 UTC, bnagirniak approved these changes
Tested after conflicts fix - works ok

2021-11-25 16:29 UTC, VascoPi approved these changes
Works well.

2021-11-26 22:31 UTC, merged