RPRBLND-1997: Improve Matlib progress + status update
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #154
Opened 2021-11-25 14:13 UTC by VascoPi

### PURPOSE
Improve status update, progress. Handle connection error.

### EFFECT OF CHANGE
Added refresh button. Improved status. Update sync and download progress. Support connection error. 

### TECHNICAL STEPS
Added function update_ui.
Added operator HDUSD_MATLIB_OP_sync_materials.
Added handle connection error.
Added set_status, is_connection methods for Manager.

2021-11-26 15:27 UTC, bnagirniak requested changes
UI changes discussed offline. Move  try...except blocks to higher level.

2021-11-26 15:27 UTC, bnagirniak commented on src/hdusd/ui/matlib.py
> +            manager.status = "No materials found" if not materials else f"{str(len(materials))} materials"
f"{len(materials)} materials"

2021-11-26 15:27 UTC, bnagirniak commented on src/hdusd/utils/matlib.py
> +def update_ui(area_type="PROPERTIES", region_type="WINDOW"):
Maybe move this tool to utils\init?

2021-11-26 15:27 UTC, bnagirniak commented on src/hdusd/utils/matlib.py
> +    if cache_check and path.is_file() and path.suffix != ".raw":
remove `path.suffix != ".raw"`

2021-11-26 15:27 UTC, bnagirniak commented on src/hdusd/utils/matlib.py
> +    except (requests.ConnectionError, requests.Timeout) as exception:
Let's catch exception on top level inside threadpool workers.

2021-12-01 16:13 UTC, VascoPi commented
Moved to [https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/pull/161](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/pull/161)

2021-12-01 16:13 UTC, closed without merging