RPRBLND-2030: Selected light source showed orange with GL Delegate
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #173
Opened 2021-12-16 16:45 UTC by DagerD

### PURPOSE
Materials become red if user clicks on scene in viewport render using GL delegate

### EFFECT OF CHANGE
Fixed issue with GL delegate in viewport render when materials become red if user clicks in scene

### TECHNICAL STEPS
added parameter `l.isDomeLight = True` for SimpleLight. Now it's created every time for GL delegate

### NOTES FOR REVIEWERS
There is the same issue with material preview, which can't be fixed right now.
Warnings in console:
- `Dome light has no texture asset path.` 
- `Invalid texture for dome light environment map`
- `Could not open dome light texture file`

also known and can't be fixed right now

2021-12-16 17:33 UTC, bnagirniak requested changes
There are still red light issues

2021-12-16 17:33 UTC, bnagirniak commented on src/hdusd/engine/viewport_engine.py
> +            if not self.shading_data.type == 'MATERIAL':
Still have red light in viewport material preview.
Also after switching from material preview to rendered red light remains.
Please fix this.

2022-01-10 15:10 UTC, VascoPi approved these changes
Works well as expected.

2022-01-18 11:59 UTC, bnagirniak approved these changes

2022-01-18 18:28 UTC, merged