RPRBLND-2016: Improve Material X editor workflow
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #177
Opened 2021-12-20 08:37 UTC by VascoPi

### PURPOSE
Need to fix material X Editor workflow, because now MaterialX selection doesn't work as expected.

### EFFECT OF CHANGE
MaterialX selection in nodetree editor works as expected.

### TECHNICAL STEPS
Added update_material_iu function.
Added turn on/off for bpy.types.NODE_HT_header updates.
Added condition for nodetree pin option.

### NOTES FOR REVIEWERS
There's a workaround for Blender 3.0 because of changing logic. For Blender 3.0 implemented only the pin option.

2021-12-23 08:20 UTC, bnagirniak reviewed
Tested - works ok, suggested code improvement.

2021-12-23 08:20 UTC, bnagirniak commented on src/hdusd/utils/mx.py
> +def update_material_iu(self, context):
Move this function to ui/material.py as more related.

2021-12-23 08:31 UTC, bnagirniak requested changes
Error found in console:
```
Traceback (most recent call last):
  File "D:\blender\blender-2.93.0-f240b5e5f712-windows64\2.93\scripts\modules\bpy_types.py", line 807, in draw_ls
    func(self, context)
  File "D:\amd-gpuopen\BlenderUSDHydraAddon\src\hdusd\utils\mx.py", line 302, in update_material_iu
    if space.node_tree != mat.node_tree:
AttributeError: 'NoneType' object has no attribute 'node_tree'
```

2021-12-24 09:22 UTC, DagerD requested changes
If we have MatX attached and then try to switch from shader nodetree to MatX nodetree, MatX will be detached and swtich won't happen.

2022-01-12 16:20 UTC, VascoPi commented
Please don't merge till new usability isn't approved by Q&A .

2022-01-14 19:45 UTC, bnagirniak commented
Let's wait for @ARozghon to test

2022-01-18 16:10 UTC, bnagirniak approved these changes
Tested - works ok

2022-01-20 07:37 UTC, DagerD commented on src/hdusd/ui/material.py
> +def update_material_iu(self, context):
typo "update_material_ui"

2022-01-20 07:38 UTC, DagerD reviewed
commented in code

2022-01-21 07:10 UTC, DagerD approved these changes

2022-01-24 19:16 UTC, bsavery commented
@ARozghon  ?

2022-01-24 19:25 UTC, ARozghon commented
Looked at the latest autotests and we have an issue with coatColor.png test case with RDNA and RDNA2 GPUs https://cis.nas.luxoft.com/BlenderUSDHydraPluginAuto/PR-177/19/Test_Report_RPR/AMD_RX6800-Windows-regression.json~/Results/BlenderUSDHydra/MaterialX_Standart_Surface/report.html?searchText=USD_BL_MTX_SS_058
https://cis.nas.luxoft.com/BlenderUSDHydraPluginAuto/PR-177/19/Test_Report_RPR/AMD_RX5700XT-Windows-regression.json~/Results/BlenderUSDHydra/MaterialX_Standart_Surface/report.html?searchText=USD_BL_MTX_SS_058
but not reproduce manually with 6800 XT and driver 22.1.2
please, doublecheck before the merge

2022-01-25 07:52 UTC, ARozghon commented
manual tests on 6800 XT complete without any issues

2022-01-25 07:52 UTC, ARozghon approved these changes
manually working fine, need to update autotests

2022-01-25 15:56 UTC, merged