RPR delegate build improvements
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #275
Opened 2023-08-23 17:00 UTC by VascoPi

### PURPOSE
Install requirements outside blender’s python.

### EFFECT OF CHANGE
Automatic installation requirements.txt within the build process.

### TECHNICAL STEPS

Removed redundant imports.
Remove redundant requirements.
Added install_requirements and uninstall_requirements. Including verification of whether the module is installed.

2023-08-25 10:40 UTC, DagerD requested changes

2023-08-25 10:40 UTC, DagerD commented on build.py
> +        uninstall_requirements(py_exe)
Doesn't have second argument

2023-08-28 11:10 UTC, DagerD reviewed
Is it fine that we call `install_requirements` and `uninstall_requirements` 2 times (`def_usd` and `def_hdrpr`)?

2023-08-30 13:26 UTC, DagerD approved these changes
Works fine

2023-08-30 15:00 UTC, ARozghon approved these changes
all devs approved and QA approved

2023-08-30 19:15 UTC, merged