[RPRBLND-1704] Convert Image Texture to MaterialX
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #49
Opened 2021-04-22 14:39 UTC by ardraeiss

### PURPOSE
Convert Blender Image Texture shader node to MaterialX format.

### EFFECT OF CHANGE
- added Image Texture node support.

### TECHNICAL STEPS
- added Image Texture node converter;
- added Image Texture node to shader nodes menu.

### NOTES
- Only images in separate files are exported for now. Next step will be to export packed/edited images.

2021-04-23 11:16 UTC, bnagirniak requested changes
commented in code

2021-04-23 11:16 UTC, bnagirniak commented on src/hdusd/bl_nodes/nodes/texture.py
> +        if image.source != 'FILE':
pixels can be exported to temporary image file like .exr. Look as example into export.material.sync_mx()

2021-04-23 11:16 UTC, bnagirniak commented on src/hdusd/bl_nodes/nodes/texture.py
> +        result = self.create_node('image', 'color4', {
color3?

2021-04-27 17:16 UTC, ardraeiss commented on src/hdusd/bl_nodes/nodes/texture.py
> +        image_error_result = self.node_item((1.0, 0.0, 1.0, 1.0))
Extracted to other image textures-related constants in the same module

2021-04-27 19:16 UTC, bnagirniak approved these changes
Code is ok.

2021-04-27 21:36 UTC, merged