RPRBLND-1841: add External Data options support
GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon pull request #86
Opened 2021-08-13 16:58 UTC by DagerD

### PURPOSE
Need to add support for the External Data option support

### EFFECT OF CHANGE

- Changed UI for file selection for nodes in texture2d and texture3d node categories
- Extended Data now works (tested with images)

### TECHNICAL STEPS

- Reworked MaterialX classes builder. Now image selector is PointerProperty
- Changed UI for file selection in nodes
- Added cache_image_file method for cache images in temp dir.

Also added handle for exception which happens sometimes when on/off viewport rendering (`ReferenceError: StructRNA of type HdUSDEngine has been removed`)

### NOTES FOR REVIEWERS
You need to rebuild MaterialX classes to see the changes.

2021-08-16 11:14 UTC, bnagirniak requested changes
MxNode.compute() should be adjusted.

2021-08-16 11:14 UTC, bnagirniak commented on src/hdusd/mx_nodes/node_tree.py
> +        ng = bpy.data.node_groups.get(self.name, None)
This whole code is not needed here

2021-08-16 11:18 UTC, bnagirniak commented on src/hdusd/engine/viewport_engine.py
> +            self.render_engine.tag_redraw()
Probably error is happen earlier, please check.

2021-08-17 08:14 UTC, VascoPi approved these changes
Tested, no errors, works well.

2021-08-17 17:00 UTC, bnagirniak approved these changes
Tested - works good now.

2021-08-18 20:21 UTC, merged